language: node_js

node_js:
    - stable

cache: yarn

install:
    - yarn

script:
    - yarn lint

branches:
    only:
        - master

before_deploy:
    - next build && next export && touch out/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: out
  github-token: $GITHUB_TOKEN
  on:
    branch: master
